import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'it' | 'zh' | 'de' | 'pt' | 'ja' | 'ko' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    hero_title: "Use Stablecoins to Power Global Payments",
    hero_subtitle: "We help individuals, startups, Web3 teams, and emerging fintechs design simple, compliant payment flows using stablecoins — no need for legacy rails or expensive intermediaries.",
    view_packages: "View Our Packages",
    get_started: "Get Started",
    why_choose: "Why Choose Stablecoin Payments?",
    instant_transfers: "Instant Transfers",
    instant_transfers_desc: "Cross-border payments in minutes, not days",
    lower_fees: "Lower Fees",
    lower_fees_desc: "Reduce costs by up to 90% vs traditional banks",
    wallet_native: "Wallet-Native",
    wallet_native_desc: "Works with crypto wallets — no bank needed",
    global_reach: "Global Reach",
    global_reach_desc: "Ideal for remote teams and international payouts",
    transparent: "Transparent",
    transparent_desc: "Trackable, programmable, and fully auditable",
    compliant: "Compliant",
    compliant_desc: "Navigate regulations across multiple jurisdictions",
    scalable: "Scalable",
    scalable_desc: "Scale to $100M+ monthly volume capacity",
    operations_24_7: "24/7 Operations",
    operations_24_7_desc: "No banking hours - payments work around the clock",
    built_for_era: "Built for the New Era of Digital Currencies",
    our_packages: "Our Packages",
    starter: "Starter",
    growth: "Growth",
    scale: "Scale",
    get_started_today: "Get Started Today",
    name: "Name",
    email: "Email",
    company: "Company / Project",
    region: "Region / Country",
    use_case: "Use Case",
    package: "Interested Package",
    comments: "Additional Comments",
    submit: "Submit"
  },
  es: {
    hero_title: "Usa Stablecoins para Impulsar Pagos Globales",
    hero_subtitle: "Ayudamos a individuos, startups, equipos Web3 y fintechs emergentes a diseñar flujos de pago simples y conformes usando stablecoins — sin necesidad de rieles heredados o intermediarios costosos.",
    view_packages: "Ver Nuestros Paquetes",
    get_started: "Comenzar",
    why_choose: "¿Por Qué Elegir Pagos con Stablecoin?",
    instant_transfers: "Transferencias Instantáneas",
    instant_transfers_desc: "Pagos transfronterizos en minutos, no días",
    lower_fees: "Tarifas Más Bajas",
    lower_fees_desc: "Reduce costos hasta 90% vs bancos tradicionales",
    wallet_native: "Nativo de Wallet",
    wallet_native_desc: "Funciona con wallets crypto — no se necesita banco",
    global_reach: "Alcance Global",
    global_reach_desc: "Ideal para equipos remotos y pagos internacionales",
    transparent: "Transparente",
    transparent_desc: "Rastreable, programable y completamente auditable",
    compliant: "Conforme",
    compliant_desc: "Navega regulaciones en múltiples jurisdicciones",
    scalable: "Escalable",
    scalable_desc: "Escala a capacidad de $100M+ volumen mensual",
    operations_24_7: "Operaciones 24/7",
    operations_24_7_desc: "Sin horarios bancarios - pagos funcionan todo el día",
    built_for_era: "Construido para la Nueva Era de Monedas Digitales",
    our_packages: "Nuestros Paquetes",
    starter: "Iniciador",
    growth: "Crecimiento",
    scale: "Escala",
    get_started_today: "Comienza Hoy",
    name: "Nombre",
    email: "Correo",
    company: "Empresa / Proyecto",
    region: "Región / País",
    use_case: "Caso de Uso",
    package: "Paquete de Interés",
    comments: "Comentarios Adicionales",
    submit: "Enviar"
  },
  fr: {
    hero_title: "Utilisez les Stablecoins pour Alimenter les Paiements Globaux",
    hero_subtitle: "Nous aidons les individus, startups, équipes Web3 et fintechs émergentes à concevoir des flux de paiement simples et conformes utilisant les stablecoins — sans besoin de rails hérités ou d'intermédiaires coûteux.",
    view_packages: "Voir Nos Forfaits",
    get_started: "Commencer",
    why_choose: "Pourquoi Choisir les Paiements Stablecoin?",
    instant_transfers: "Transferts Instantanés",
    instant_transfers_desc: "Paiements transfrontaliers en minutes, pas en jours",
    lower_fees: "Frais Réduits",
    lower_fees_desc: "Réduisez les coûts jusqu'à 90% vs banques traditionnelles",
    wallet_native: "Natif Wallet",
    wallet_native_desc: "Fonctionne avec les wallets crypto — pas besoin de banque",
    global_reach: "Portée Mondiale",
    global_reach_desc: "Idéal pour équipes distantes et paiements internationaux",
    transparent: "Transparent",
    transparent_desc: "Traçable, programmable et entièrement auditable",
    compliant: "Conforme",
    compliant_desc: "Naviguez les réglementations dans plusieurs juridictions",
    scalable: "Évolutif",
    scalable_desc: "Évoluez vers une capacité de volume mensuel de 100M$+",
    operations_24_7: "Opérations 24/7",
    operations_24_7_desc: "Pas d'heures bancaires - paiements fonctionnent 24h/24",
    built_for_era: "Conçu pour la Nouvelle Ère des Monnaies Numériques",
    our_packages: "Nos Forfaits",
    starter: "Débutant",
    growth: "Croissance",
    scale: "Échelle",
    get_started_today: "Commencez Aujourd'hui",
    name: "Nom",
    email: "Email",
    company: "Entreprise / Projet",
    region: "Région / Pays",
    use_case: "Cas d'Usage",
    package: "Forfait d'Intérêt",
    comments: "Commentaires Supplémentaires",
    submit: "Soumettre"
  },
  de: {
    hero_title: "Nutzen Sie Stablecoins für Globale Zahlungen",
    hero_subtitle: "Wir helfen Einzelpersonen, Startups, Web3-Teams und aufstrebenden Fintechs dabei, einfache, konforme Zahlungsabläufe mit Stablecoins zu entwickeln — ohne Legacy-Systeme oder teure Zwischenhändler.",
    view_packages: "Unsere Pakete Ansehen",
    get_started: "Loslegen",
    why_choose: "Warum Stablecoin-Zahlungen Wählen?",
    instant_transfers: "Sofortübertragungen",
    instant_transfers_desc: "Grenzüberschreitende Zahlungen in Minuten, nicht Tagen",
    lower_fees: "Niedrigere Gebühren",
    lower_fees_desc: "Reduzieren Sie Kosten um bis zu 90% vs traditionelle Banken",
    wallet_native: "Wallet-Nativ",
    wallet_native_desc: "Funktioniert mit Krypto-Wallets — keine Bank erforderlich",
    global_reach: "Globale Reichweite",
    global_reach_desc: "Ideal für Remote-Teams und internationale Auszahlungen",
    transparent: "Transparent",
    transparent_desc: "Verfolgbar, programmierbar und vollständig überprüfbar",
    compliant: "Konform",
    compliant_desc: "Navigieren Sie Vorschriften in mehreren Jurisdiktionen",
    scalable: "Skalierbar",
    scalable_desc: "Skalieren Sie auf 100M$+ monatliche Volumenkapazität",
    operations_24_7: "24/7 Betrieb",
    operations_24_7_desc: "Keine Bankzeiten - Zahlungen funktionieren rund um die Uhr",
    built_for_era: "Entwickelt für die Neue Ära Digitaler Währungen",
    our_packages: "Unsere Pakete",
    starter: "Starter",
    growth: "Wachstum",
    scale: "Skalierung",
    get_started_today: "Heute Beginnen",
    name: "Name",
    email: "E-Mail",
    company: "Unternehmen / Projekt",
    region: "Region / Land",
    use_case: "Anwendungsfall",
    package: "Interessiertes Paket",
    comments: "Zusätzliche Kommentare",
    submit: "Absenden"
  },
  pt: {
    hero_title: "Use Stablecoins para Impulsionar Pagamentos Globais",
    hero_subtitle: "Ajudamos indivíduos, startups, equipes Web3 e fintechs emergentes a projetar fluxos de pagamento simples e conformes usando stablecoins — sem necessidade de sistemas legados ou intermediários caros.",
    view_packages: "Ver Nossos Pacotes",
    get_started: "Começar",
    why_choose: "Por Que Escolher Pagamentos Stablecoin?",
    instant_transfers: "Transferências Instantâneas",
    instant_transfers_desc: "Pagamentos transfronteiriços em minutos, não dias",
    lower_fees: "Taxas Mais Baixas",
    lower_fees_desc: "Reduza custos em até 90% vs bancos tradicionais",
    wallet_native: "Nativo de Carteira",
    wallet_native_desc: "Funciona com carteiras crypto — sem necessidade de banco",
    global_reach: "Alcance Global",
    global_reach_desc: "Ideal para equipes remotas e pagamentos internacionais",
    transparent: "Transparente",
    transparent_desc: "Rastreável, programável e totalmente auditável",
    compliant: "Conforme",
    compliant_desc: "Navegue regulamentações em múltiplas jurisdições",
    scalable: "Escalável",
    scalable_desc: "Escale para capacidade de volume mensal de $100M+",
    operations_24_7: "Operações 24/7",
    operations_24_7_desc: "Sem horários bancários - pagamentos funcionam 24 horas",
    built_for_era: "Construído para a Nova Era das Moedas Digitais",
    our_packages: "Nossos Pacotes",
    starter: "Iniciante",
    growth: "Crescimento",
    scale: "Escala",
    get_started_today: "Comece Hoje",
    name: "Nome",
    email: "Email",
    company: "Empresa / Projeto",
    region: "Região / País",
    use_case: "Caso de Uso",
    package: "Pacote de Interesse",
    comments: "Comentários Adicionais",
    submit: "Enviar"
  },
  it: {
    hero_title: "Usa le Stablecoin per Alimentare i Pagamenti Globali",
    hero_subtitle: "Aiutiamo individui, startup, team Web3 e fintech emergenti a progettare flussi di pagamento semplici e conformi utilizzando stablecoin — senza bisogno di sistemi legacy o intermediari costosi.",
    view_packages: "Visualizza i Nostri Pacchetti",
    get_started: "Inizia",
    why_choose: "Perché Scegliere i Pagamenti Stablecoin?",
    instant_transfers: "Trasferimenti Istantanei",
    instant_transfers_desc: "Pagamenti transfrontalieri in minuti, non giorni",
    lower_fees: "Commissioni Più Basse",
    lower_fees_desc: "Riduci i costi fino al 90% vs banche tradizionali",
    wallet_native: "Nativo del Wallet",
    wallet_native_desc: "Funziona con wallet crypto — nessuna banca necessaria",
    global_reach: "Portata Globale",
    global_reach_desc: "Ideale per team remoti e pagamenti internazionali",
    transparent: "Trasparente",
    transparent_desc: "Tracciabile, programmabile e completamente verificabile",
    compliant: "Conforme",
    compliant_desc: "Naviga le normative in più giurisdizioni",
    scalable: "Scalabile",
    scalable_desc: "Scala a capacità di volume mensile di $100M+",
    operations_24_7: "Operazioni 24/7",
    operations_24_7_desc: "Nessun orario bancario - pagamenti funzionano 24 ore",
    built_for_era: "Costruito per la Nuova Era delle Valute Digitali",
    our_packages: "I Nostri Pacchetti",
    starter: "Starter",
    growth: "Crescita",
    scale: "Scala",
    get_started_today: "Inizia Oggi",
    name: "Nome",
    email: "Email",
    company: "Azienda / Progetto",
    region: "Regione / Paese",
    use_case: "Caso d'Uso",
    package: "Pacchetto di Interesse",
    comments: "Commenti Aggiuntivi",
    submit: "Invia"
  },
  zh: {
    hero_title: "使用稳定币推动全球支付",
    hero_subtitle: "我们帮助个人、初创公司、Web3团队和新兴金融科技公司设计使用稳定币的简单、合规支付流程——无需传统轨道或昂贵的中介机构。",
    view_packages: "查看我们的套餐",
    get_started: "开始使用",
    why_choose: "为什么选择稳定币支付？",
    instant_transfers: "即时转账",
    instant_transfers_desc: "跨境支付分钟完成，而非天数",
    lower_fees: "更低费用",
    lower_fees_desc: "相比传统银行降低成本高达90%",
    wallet_native: "钱包原生",
    wallet_native_desc: "与加密钱包配合使用——无需银行",
    global_reach: "全球覆盖",
    global_reach_desc: "适合远程团队和国际支付",
    transparent: "透明",
    transparent_desc: "可追踪、可编程且完全可审计",
    compliant: "合规",
    compliant_desc: "导航多个司法管辖区的法规",
    scalable: "可扩展",
    scalable_desc: "扩展至每月1亿美元+容量",
    operations_24_7: "24/7运营",
    operations_24_7_desc: "无银行营业时间限制——支付全天候运行",
    built_for_era: "为数字货币新时代而建",
    our_packages: "我们的套餐",
    starter: "入门版",
    growth: "成长版",
    scale: "规模版",
    get_started_today: "今天开始",
    name: "姓名",
    email: "邮箱",
    company: "公司/项目",
    region: "地区/国家",
    use_case: "使用案例",
    package: "感兴趣的套餐",
    comments: "其他评论",
    submit: "提交"
  },
  ja: {
    hero_title: "ステーブルコインでグローバル決済を強化",
    hero_subtitle: "私たちは個人、スタートアップ、Web3チーム、新興フィンテックがステーブルコインを使用してシンプルで準拠した決済フローを設計するのを支援します。従来のレールや高額な仲介業者は不要です。",
    view_packages: "パッケージを見る",
    get_started: "始める",
    why_choose: "なぜステーブルコイン決済を選ぶのか？",
    instant_transfers: "即座の送金",
    instant_transfers_desc: "国境を越えた決済が日数ではなく分単位で",
    lower_fees: "低い手数料",
    lower_fees_desc: "従来の銀行と比較してコストを最大90%削減",
    wallet_native: "ウォレットネイティブ",
    wallet_native_desc: "暗号ウォレットで動作——銀行不要",
    global_reach: "グローバルリーチ",
    global_reach_desc: "リモートチームと国際的な支払いに最適",
    transparent: "透明",
    transparent_desc: "追跡可能、プログラム可能、完全監査可能",
    compliant: "準拠",
    compliant_desc: "複数の管轄区域での規制をナビゲート",
    scalable: "スケーラブル",
    scalable_desc: "月間1億ドル+の容量まで拡張",
    operations_24_7: "24/7運営",
    operations_24_7_desc: "銀行営業時間なし——決済は24時間動作",
    built_for_era: "デジタル通貨の新時代のために構築",
    our_packages: "私たちのパッケージ",
    starter: "スターター",
    growth: "成長",
    scale: "スケール",
    get_started_today: "今日始める",
    name: "名前",
    email: "メール",
    company: "会社/プロジェクト",
    region: "地域/国",
    use_case: "使用例",
    package: "興味のあるパッケージ",
    comments: "追加コメント",
    submit: "送信"
  },
  ko: {
    hero_title: "스테이블코인으로 글로벌 결제 강화",
    hero_subtitle: "우리는 개인, 스타트업, Web3 팀, 신흥 핀테크가 스테이블코인을 사용하여 간단하고 규정을 준수하는 결제 흐름을 설계하도록 도와줍니다. 레거시 레일이나 비싼 중개업체가 필요하지 않습니다.",
    view_packages: "패키지 보기",
    get_started: "시작하기",
    why_choose: "왜 스테이블코인 결제를 선택하나요?",
    instant_transfers: "즉시 송금",
    instant_transfers_desc: "국경을 넘나드는 결제를 일 단위가 아닌 분 단위로",
    lower_fees: "낮은 수수료",
    lower_fees_desc: "기존 은행 대비 비용을 최대 90% 절감",
    wallet_native: "지갑 네이티브",
    wallet_native_desc: "암호화폐 지갑과 함께 작동 — 은행 불필요",
    global_reach: "글로벌 도달",
    global_reach_desc: "원격 팀과 국제 지급에 이상적",
    transparent: "투명한",
    transparent_desc: "추적 가능, 프로그래밍 가능, 완전 감사 가능",
    compliant: "규정 준수",
    compliant_desc: "여러 관할권의 규정 탐색",
    scalable: "확장 가능",
    scalable_desc: "월 1억 달러+ 용량까지 확장",
    operations_24_7: "24/7 운영",
    operations_24_7_desc: "은행 영업시간 없음 — 결제는 24시간 작동",
    built_for_era: "디지털 화폐의 새로운 시대를 위해 구축",
    our_packages: "우리의 패키지",
    starter: "스타터",
    growth: "성장",
    scale: "스케일",
    get_started_today: "오늘 시작하기",
    name: "이름",
    email: "이메일",
    company: "회사/프로젝트",
    region: "지역/국가",
    use_case: "사용 사례",
    package: "관심 있는 패키지",
    comments: "추가 의견",
    submit: "제출"
  },
  ar: {
    hero_title: "استخدم العملات المستقرة لتشغيل المدفوعات العالمية",
    hero_subtitle: "نحن نساعد الأفراد والشركات الناشئة وفرق Web3 وشركات التكنولوجيا المالية الناشئة على تصميم تدفقات دفع بسيطة ومتوافقة باستخدام العملات المستقرة — دون الحاجة إلى أنظمة قديمة أو وسطاء مكلفين.",
    view_packages: "عرض حزمنا",
    get_started: "ابدأ",
    why_choose: "لماذا تختار مدفوعات العملة المستقرة؟",
    instant_transfers: "تحويلات فورية",
    instant_transfers_desc: "مدفوعات عبر الحدود في دقائق، وليس أيام",
    lower_fees: "رسوم أقل",
    lower_fees_desc: "قلل التكاليف بنسبة تصل إلى 90٪ مقابل البنوك التقليدية",
    wallet_native: "أصلي للمحفظة",
    wallet_native_desc: "يعمل مع محافظ العملات المشفرة — لا حاجة لبنك",
    global_reach: "وصول عالمي",
    global_reach_desc: "مثالي للفرق البعيدة والمدفوعات الدولية",
    transparent: "شفاف",
    transparent_desc: "قابل للتتبع، قابل للبرمجة، وقابل للمراجعة بالكامل",
    compliant: "متوافق",
    compliant_desc: "التنقل في اللوائح عبر عدة اختصاصات",
    scalable: "قابل للتوسع",
    scalable_desc: "توسع إلى سعة حجم شهري 100 مليون دولار+",
    operations_24_7: "عمليات 24/7",
    operations_24_7_desc: "لا ساعات مصرفية — المدفوعات تعمل على مدار الساعة",
    built_for_era: "مبني لعصر العملات الرقمية الجديد",
    our_packages: "حزمنا",
    starter: "البادئ",
    growth: "النمو",
    scale: "المقياس",
    get_started_today: "ابدأ اليوم",
    name: "الاسم",
    email: "البريد الإلكتروني",
    company: "الشركة / المشروع",
    region: "المنطقة / البلد",
    use_case: "حالة الاستخدام",
    package: "الحزمة المهتم بها",
    comments: "تعليقات إضافية",
    submit: "إرسال"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  console.log('LanguageProvider: Current language is', language);

  const t = (key: string): string => {
    const translation = translations[language]?.[key as keyof typeof translations['en']];
    console.log(`Translation for "${key}" in ${language}:`, translation || key);
    return translation || key;
  };

  const handleLanguageChange = (lang: Language) => {
    console.log('LanguageProvider: Changing language from', language, 'to', lang);
    setLanguage(lang);
  };

  useEffect(() => {
    console.log('LanguageProvider: Language changed to', language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleLanguageChange, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
